project_id = "wsbuqiznddvxcwvpnbxm"

[functions.generate-magic-link]
verify_jwt = false

[functions.verify-magic-link]
verify_jwt = false

[functions.login-by-pin]
verify_jwt = false

[functions.login-by-plate]
verify_jwt = false
