// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Clave publishable (nueva API key de Supabase, reemplaza la anon legacy). Es
// pública por diseño; la seguridad recae en RLS. Se lee del entorno (VITE_*) con
// fallback al valor actual para no romper builds sin variable configurada.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? "https://wsbuqiznddvxcwvpnbxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  "sb_publishable_7kE-XLp_jL_fPq2XqVOSMg_IejPqbdy";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});